### ISSUE TITLE
NCAA map

### ISSUE THREAD

**Issue by Slugger** [livepvrdata-oss/livepvrdata-svc#1]
Here's the NCAA map exported from the appengine app.  There's about 50 schools in the map.  Of course this is no where near complete, but with this map plus the schools that don't need a map, you end up catching at least 70% of all games and 90% of "Top 25" games, which is what the majority of users will be monitoring anyways.

Probably easiest to just add this as a static map that's created on startup.  With this map, you _might_ be able to get away with going to an in-memory only db for SRE.  The caveat being you'll need to update the static map and release an update any time changes are needed.  For the pro sports, that's very rare (expansion/relocation only), it's just the NCAA where the maps tend to be out of date when a "big" school plays a nobody early in a season.

[ncaa.zip](https://github.com/livepvrdata-oss/livepvrdata-svc/files/276511/ncaa.zip)

**Comment by skiingwiz** [comment]
Resolved by f72fa1a54e1080de7f97b6c5b04dd19d43334462
